recipes:
    global:
        - applications::create_var_chef_cache
    mac_os_x:
        - osxdefaults::enable_subpixel_font_rendering_on_non-apple_lcds
        - osxdefaults::finder_small_sidebar_icon_size
        - osxdefaults::automatically_illuminate_built-in_macbook_keyboard_in_low_light
        - osxdefaults::automatically_quit_printer_app_once_the_print_jobs_complete
        - osxdefaults::avoid_creating_ds_store_files_on_network_volumes
        - applications::bash
