recipes:
    global:
        - dotfiles::kms
        - dotfiles::workspace
    mac_os_x:
        - osxdefaults::disable_gatekeeper
        - osxdefaults::speed_up_mission_control_animations
        - osxdefaults::mail_check_for_new_messages
        - osxdefaults::mail_when_searching_do_not_include_trash
        - osxdefaults::mail_copy_email_addresses_instead_of_names_in_mail
        - osxdefaults::mail_disable_send_and_reply_animations_in_mail
        - osxdefaults::do_not_show_dashboard_as_a_space
        - osxdefaults::finder_allow_text_selection_in_quick_look
        - osxdefaults::finder_display_full_path
        - osxdefaults::finder_use_column_view_in_all_finder_windows_by_default
        - osxdefaults::finder_new_finder_windows_shows_homefolder
        - osxdefaults::finder_disable_the_warning_before_emptying_the_trash
        - osxdefaults::finder_disable_the_warning_when_changing_a_file_extension
        - osxdefaults::finder_search_the_current_folder_by_default
